import React,{useState} from 'react';
import {useGatekeeper} from '../store';
import {Icon} from '../components';
import {CollegeLogo, CampusPhoto, collegeName} from '../college';
export default function Login({admin=false,destination='admin'}) {
  const g=useGatekeeper();const [show,setShow]=useState(false);const [error,setError]=useState('');
  return <div className="login-page"><section className="login-art"><a className="brand" href="#login"><div className="brand-mark"><CollegeLogo/></div><strong>GATEKEEPER <b className="brand-version">v2</b><span>ASIET CAMPUS SECURITY</span></strong></a><div className="login-story"><div className="eyebrow">Campus security platform</div><h1>Campus access.<br/>Centralized control.</h1><p>Verify identities, manage access permissions, and review campus activity in one workspace.</p><CampusPhoto/></div><div className="login-institution">{collegeName}<span>Kalady, Kerala · Campus Safety Division</span></div></section><section className="login-form-side"><div className="login-top"><Icon name="science" size={16}/> {g.local?(g.cloud?'Turso cloud database':'Local database installation'):'Demonstration environment'}</div><div className="login-card"><div className="login-symbol"><Icon name={admin?'admin_panel_settings':'badge'} size={28}/></div><div className="eyebrow">{admin?'Administrator access':'Officer access'}</div><h2>{admin?'Administrator sign in':'Checkpoint sign in'}</h2><p>{admin?'Manage campus permissions and review the audit ledger.':'Sign in to start verifying campus IDs and recording transit.'}</p>{g.connection?.setupRequired&&<div className="form-error" role="status"><strong>Connect your cloud database</strong><p>{g.connection.message}</p><p>Create a Turso libSQL database, then copy .env.server.example to .env.server and fill in its URL, token, and your login passwords.</p></div>}<form onSubmit={async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));if(g.local){try{const user=await g.login(data.id,data.password);if(admin&&user.role!=='admin'){g.setSession(null);return setError('Administrator account required.');}location.hash=admin?destination:'scanner';}catch(error){setError(error.message);}return;}if(data.id!==(admin?'ADM-ASIET-001':'SEC-G1-204')||data.password!==(admin?'admin-demo':'gatekeeper'))return setError(admin?'Invalid administrator ID or password.':'Use the demo credentials shown below.');g.setSession({id:data.id,role:admin?'admin':'guard',adminUnlocked:admin,gate:data.gate});location.hash=admin?destination:'scanner';}}>
      <label>Assigned checkpoint<select name="gate"><option>Gate 1</option></select></label><label>{admin?'Administrator ID':'Officer ID'}<input name="id" required defaultValue={admin?'ADM-ASIET-001':'SEC-G1-204'} autoComplete="username"/></label><label>Terminal password<div className="password-input"><input name="password" type={show?'text':'password'} required defaultValue={g.local?'':admin?'':'gatekeeper'} autoComplete="current-password"/><button type="button" aria-label={show?'Hide password':'Show password'} onClick={()=>setShow(!show)}><Icon name={show?'visibility_off':'visibility'} size={20}/></button></div></label>{error&&<p className="form-error" role="alert">{error}</p>}<button type="submit" className="primary login-submit"><Icon name="lock_open"/> {admin?'Open administration':'Open checkpoint'} <Icon name="arrow_forward"/></button>
    </form>{admin?<p className="admin-access-note">Enter your administrator credentials to view records and management tools. Returning to the scanner locks this access.</p>:g.local?<p className="admin-access-note">Use the officer password configured for this installation. Pending scans resume after sign-in.</p>:<div className="demo-credentials"><Icon name="info" size={18}/><div><strong>Demo credentials</strong><p>Demo ID: <code>{admin?'ADM-ASIET-001':'SEC-G1-204'}</code><br/>Password: <code>{admin?'admin-demo':'gatekeeper'}</code></p></div></div>}<a className="login-switch" href={admin?(g.session?'#scanner':'#login'):'#admin-login'}>{admin?'Return to officer checkpoint':'Administrator access'}<Icon name="arrow_forward" size={17}/></a></div><p className="login-disclaimer">{g.local?(g.cloud?'Turso cloud storage':'Local SQLite storage')+' · No physical gate connection':'Frontend demo · No connection to physical gates or institutional systems'}</p></section></div>;
}
